[versions]
dokka = "1.9.10"
konf = "1.1.2"
kotest = "5.7.2"
kotlin = "1.7.22"
mockito = "4.11.0"

[libraries]
classgraph = "io.github.classgraph:classgraph:4.8.163"
konf-yaml = { module = "com.uchuhimo:konf-yaml", version.ref = "konf" }
kotest-junit5-jvm = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
kotest-assertions-core-jvm = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
kotlin-compiler = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
dokka-core = { module = "org.jetbrains.dokka:dokka-core", version.ref = "dokka" }
dokka-dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
dokka-javadoc-plugin = { module = "org.jetbrains.dokka:javadoc-plugin", version.ref = "dokka" }

[bundles]
dokka = [ "dokka-core", "dokka-dokka-gradle-plugin", "dokka-javadoc-plugin" ]
kotlin-testing = [ "kotest-junit5-jvm", "kotest-assertions-core-jvm", "mockito-core" ]

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gitSemVer = { id = "org.danilopianini.git-sensitive-semantic-versioning", version = "0.3.0" }
gradlePluginPublish = { id = "com.gradle.plugin-publish", version = "1.0.0" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-qa = { id = "org.danilopianini.gradle-kotlin-qa", version = "0.27.1" }
multiJvmTesting = { id = "org.danilopianini.multi-jvm-test-plugin", version = "0.4.23" }
publishOnCentral = { id = "org.danilopianini.publish-on-central", version = "5.0.10" }
taskTree = { id = "com.dorongold.task-tree", version = "2.1.1" }
