[versions]
dokka = "1.9.20"
kotest = "5.9.1"
kotlin = "2.0.21"
mockito = "5.14.2"

[libraries]
kotest-junit5-jvm = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
kotest-assertions-core-jvm = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
kotlin-compiler = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
dokka-core = { module = "org.jetbrains.dokka:dokka-core", version.ref = "dokka" }
dokka-dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
dokka-javadoc-plugin = { module = "org.jetbrains.dokka:javadoc-plugin", version.ref = "dokka" }

[bundles]
dokka = [ "dokka-core", "dokka-dokka-gradle-plugin", "dokka-javadoc-plugin" ]
kotlin-testing = [ "kotest-junit5-jvm", "kotest-assertions-core-jvm", "mockito-core" ]

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gitSemVer = "org.danilopianini.git-sensitive-semantic-versioning:3.1.7"
gradlePluginPublish = "com.gradle.plugin-publish:1.3.0"
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-qa = "org.danilopianini.gradle-kotlin-qa:0.74.0"
multiJvmTesting = "org.danilopianini.multi-jvm-test-plugin:2.0.0"
publishOnCentral = "org.danilopianini.publish-on-central:6.0.0"
taskTree = "com.dorongold.task-tree:4.0.0"
